config/routes.rb
Rails.application.routes.draw do
  resources :campaigns
  resources :products
  devise_for :users

  root 'products#index'
  get '/auctions', to: 'products#list_campaigns', as: :list_campaigns
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction_store.rb
# == Schema Information
#
# Table name: auction_stores
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  campaign_id :integer
#  bid_price   :decimal(10, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class AuctionStore < ApplicationRecord
  belongs_to :user
  belongs_to :campaign

  validate :bid_price_must_than_big_price, on: :create
  validate :time_over

  def bid_price_must_than_big_price
    last_auction_store = AuctionStore.where(campaign: self.campaign).last
    if last_auction_store.present? && bid_price < last_auction_store.bid_price
      errors.add(:bid_price, "more than price")
    end
  end

  def time_over
    if self.campaign.time < DateTime.current
      errors.add(:time, 'time over')
    end
  end
  after_create_commit { AuctionStoreBroadcastJob.perform_later self }
end

app/models/campaign.rb
# == Schema Information
#
# Table name: campaigns
#
#  id         :integer          not null, primary key
#  product_id :integer
#  user_id    :integer
#  time       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Campaign < ApplicationRecord
  belongs_to :product
  belongs_to :user
  has_many :auction_store, dependent: :destroy
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id         :integer          not null, primary key
#  image_url  :string(255)
#  image_id   :integer
#  image_type :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Image < ApplicationRecord
  belongs_to :image, polymorphic: :true
  mount_uploader :image_url, ImageUploader
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text(65535)
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ApplicationRecord
  belongs_to :user
  has_many :images, as: :image, dependent: :destroy
  has_many :campaign, dependent: :destroy

  accepts_nested_attributes_for :images

  DEFAULT_UPDATABLE_ATTRIBUTES = [:title, :description,
                                  images_attributes: [:id, :image_url]]

  validates :description, :title, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products, dependent: :destroy
  has_many :images, as: :image, dependent: :destroy
  has_many :campaign, dependent: :destroy
  has_many :auction_store, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/auction_stores_controller.rb
class AuctionStoresController < ApplicationController
end

app/controllers/auctions_controller.rb
class AuctionStoresController < ApplicationController
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :destroy]
  before_action :list_products, only: [:new, :create]
  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.user = current_user
    @campaign.time = DateTime.current + 10.minutes
    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:product_id, :user_id, :time)
    end

    def list_products
      @products = current_user.products    
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = current_user.products
  end

  def list_campaigns
    @campaigns = Campaign.includes(:product).joins(:product).order(:time).all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user = current_user
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(Product::DEFAULT_UPDATABLE_ATTRIBUTES)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/auction_stores/_auction.html.erb
<td id="price"><%= price %></td>

app/views/auction_stores/_the_auction.html.erb
<td class="email"><%= user %></td>
<td class="price"><%= price %></td>

app/views/campaigns/_form.html.erb
<%= form_for campaign, class: 'form-horizontal' do |f| %>
  <% if campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :product_id, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.collection_select :product_id, @products, :id, :title, { prompt: true }, {class: 'form-control'} %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/campaigns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campaigns</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Product</th>
      <th>User</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr>
        <td><%= campaign.product.title %></td>
        <td><%= campaign.user.email %></td>
        <td><%= campaign.time %></td>
        <td><%= link_to 'Show', campaign, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Destroy', campaign, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Products', products_path, class: 'btn btn-primary' %></li>

<%= link_to 'New Campaign', new_campaign_path, class: 'btn btn-primary' %>

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= render 'form', campaign: @campaign %>

<%= link_to 'Back', campaigns_path %>

app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @campaign.product.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @campaign.user.email %>
</p>

<p>
  <strong>Time:</strong>
  <%= @campaign.time %>
</p>

<%= link_to 'Back', campaigns_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>Auction</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/navigation_bar' %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for product, html: { multipart: true, class: 'form-horizontal' } do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :images, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.fields_for :images, product.images.build do |image_f| %>
        <%= image_f.file_field :image_url %>
      <% end %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_the_campaign.html.erb
<% binding.pry %>
<td class="email"><%= @user %></td>
<td class="price"><%= @price %></td>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= image_tag product.images.last.try(:image_url), height: 100, weight: 100 %>
        </td>
        <td><%= product.user.email %></td>
        <td><%= link_to 'Show', product, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_product_path(product), class: 'btn btn-success' %></td>
        <td><%= link_to 'Destroy', product, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path, class: 'btn btn-primary' %>

app/views/products/list_auctions.html.erb
<p id="notice"><%= notice %></p>

<h1>Campaigns</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Product</th>
      <th>Description</th>
      <th>Image</th>
      <th>User</th>
      <th>Bigest price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campaigns.each do |campaign| %>
      <tr campaign-id="<%= campaign.id %>" id="campaign-<%= campaign.id %>">
        <td><%= campaign.product.title %></td>
        <td><%= campaign.product.description %></td>
        <td class="append"><%= image_tag campaign.product.images.last.try(:image_url), height: 100, weight: 100 %>
        </td>
        <%= render_price_user(campaign) %>
        <!-- ------------------------------- -->
        <td><input type='text' id="price"></td>
        <td><input type='submit' class="click" value="Bid"></td>
        <!-- TODO -->
        <!-- ------------------------------- -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/list_campaigns.html.erb
<p id="notice"><%= notice %></p>

<h1>Campaigns</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Product</th>
      <th>Description</th>
      <th>Image</th>
      <th>Time</th>
      <th>User</th>
      <th>Bigest price</th>
    </tr>
  </thead>

  <tbody>
    <% @campaigns.each_with_index do |campaign, index| %>
      <tr campaign-id="<%= campaign.id %>" class="campaign-<%= campaign.id %>">
        <td><%= campaign.product.title %></td>
        <td><%= campaign.product.description %></td>
        <td><%= image_tag campaign.product.images.last.try(:image_url), height: 100, weight: 100 %>
        </td>
        <td id="time-<%= index %>" class='time'></td>

        <input type="hidden" value="<%= Time.at(campaign.time) %>" id="time-campaign-<%= campaign.id %>">
        <td class="user"><%= AuctionStore.where(campaign_id: campaign.id).last.try(:user).try(:email) %></td>
        <td class="price"><%= AuctionStore.where(campaign_id: campaign.id).last.try(:bid_price) %></td>
        <!-- ------------------------------- -->
        <td><input type="number" class="bid_price form-control" /></td>
        <td><button class='btn btn-success bid'> Bid </button></td>
        <!-- TODO -->
        <!-- ------------------------------- -->
      </tr>
    <% end %>
  </tbody>
</table>
<script type="text/javascript">
  $('tbody').find('tr').each(function(index){
    $(this).find('#time-'+ index).countdown($(this).find('input[type=hidden]').val(), function(event) {
      $(this).text(
        event.strftime('%H:%M:%S')
      );
    });
    $(this).find('#time-'+ index).countdown($(this).find('input[type=hidden]').val())
      .on('update.countdown', function(event) {
        var format = '%H:%M:%S';
        $(this).html(event.strftime(format));
      })
      .on('finish.countdown', function(event) {
        $(this).html('This offer has expired!')
          .parent().addClass('disabled');
      });
  })
</script>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @product.images.last.try(:image_url), height: 100, weight: 100 %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user_id%>
</p>

<%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-success' %>
<%= link_to 'Back', products_path, class: 'btn btn-primary' %>

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Auction</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home<span class="sr-only">(current)</span></a></li>
        <li><%= link_to 'Auctions', list_campaigns_path %></li>
        <li><%= link_to 'Products', products_path %></li>
        <li><%= link_to 'Campaigns', campaigns_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <%- if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Profile</a></li>
              <li><a href="#">Setting</a></li>
              <li><a href="#">Your Auctions</a></li>
              <li><a href="#">Your Products</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
          <li> <%= link_to 'Logout', destroy_user_session_path, method: :delete%></li>
        <% else %>
          <li> <%= link_to 'Login', new_user_session_path %></li>
          <li> <%= link_to 'Register', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>